# Develop override settings

theme: minimal-mistakes-jekyll
remote_theme: null
url: http://localhost:4000

analytics:
  provider: false

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded
